version: '3'
services:
  tutor:
    build: .
    command: wait-for h:5000 -t 60 -- /bin/bash -c "rake about && bin/rails server -b '0.0.0.0'"
    working_dir: "/code"
    ports:
     - "3001:3001"
    volumes:
     - .:/code
     - /code/tmp
     - /code/log
    links:
     - h
     - redis
     - postgres
    environment:
     - REDIS_URL=redis://redis:6379/0
     - OXT_DB_HOST=postgres
  redis:
    image: "redis:latest"
  postgres:
    image: "postgres:9.5"
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=ox_tutor
     - POSTGRES_PASSWORD=ox_tutor_secret_password
     - POSTGRES_DB=ox_tutor_dev
  h:
    image: "openstax/hypothesis-server"
    command: wait-for h_postgres:5432 -t 60 -- wait-for h_elasticsearch:9200 -t 60 -- make dev add_credentials_to=/tutor-server/.env
    ports:
      - "5000:5000"
    volumes:
     - .:/tutor-server
    links:
      - h_postgres
      - h_elasticsearch
      - h_rabbit
    environment:
      - APP_URL=http://localhost:5000
      - BROKER_URL=amqp://guest:guest@h_rabbit:5672//
      - SECRET_KEY=notverysecretafterall
      - DATABASE_URL=postgresql://postgres@h_postgres/postgres
      - ELASTICSEARCH_HOST=http://h_elasticsearch:9200
      - ELASTICSEARCH_INDEX=hypothesis
      - AUTHORITY=localhost
  h_postgres:
    image: postgres:9.4-alpine
  h_elasticsearch:
    image: nickstenning/elasticsearch-icu
  h_rabbit:
    image: rabbitmq:3.6-management-alpine
volumes:
  pgdata:
